var questoes = [{"id":"0", "foto":"./img/1.jpg", "alternativas":"5", "correta":"E","explicacao":"A temperatura é o único fator capaz de mudar o valor numérico da K de equilíbrio. Como o processo é endotérmico o produto é quem vai sair favorecido. Se o produto aumenta o resultado de da K de equilíbrio também irá aumentar, visando que K<sub>c</sub>= [P]/[R]" }, 
{"id":"1", "foto":"./img/2.jpg", "alternativas":"5", "correta":"D","explicacao" : "É possível provocar alteração em um equilíbrio por variação de temperatura, de concentração de participantes da reação e pressão total sobre o sistema." },
{"id":"2", "foto":"./img/3.jpg", "alternativas":"3", "correta":"C","explicacao" : "Equações sólidas não entram no K<sub>c</sub>" },
{"id":"3", "foto":"./img/4.jpg", "alternativas":"2", "correta":"B","explicacao" : " O sistema se deslocará no sentido de minimizar essa perturbação." },
{"id":"4", "foto":"./img/5.jpg", "alternativas":"5", "correta":"C","explicacao" : "O aumento da pressão beneficia a reação com menor volume e, sabendo que a reação direta é exotérmica já que ∆H<0, a redução da temperatura favorece a reação exotérmica." },
{"id":"5", "foto":"./img/6.jpg", "alternativas":"5", "correta":"E","explicacao" : "Se K<sub>c</sub>= [P]/[R], então [3]<sup>2</sup>/[5]=1,8." },
{"id":"6", "foto":"./img/7.jpg", "alternativas":"5", "correta":"C","explicacao" : "Sem explicação" },
{"id":"7", "foto":"./img/8.jpg", "alternativas":"5", "correta":"A","explicacao" : ": 2 NO<sub>2</sub>  = reagente / NO<sub>4</sub> = produto; K<sub>c</sub> = 1/2<sup>2</sup> = 1/4 = 0,25." },
{"id":"8", "foto":"./img/9.jpg", "alternativas":"2", "correta":"A","explicacao" : "Sem explicação" },
{"id":"9", "foto":"./img/10.jpg", "alternativas":"5", "correta":"B","explicacao" : "Sem explicação" },
{"id":"10", "foto":"./img/11.jpg", "alternativas":"4", "correta":"C","explicacao" : "Sem explicação" },
{"id":"11", "foto":"./img/12.jpg", "alternativas":"4", "correta":"D","explicacao" : "Sem explicação" }];